import { describe, expect, it } from 'vitest';
import {
  extractGcodeStats,
  parseDurationToSeconds,
} from './modules/printrepo/utils/gcodeStats';

describe('parseDurationToSeconds', () => {
  it('formato compacto PrusaSlicer', () => {
    expect(parseDurationToSeconds('2h 15m 30s')).toBe(8130);
    expect(parseDurationToSeconds('1d 3h 2m 15s')).toBe(97335);
  });

  it('palabras largas (Simplify3D en inglés)', () => {
    expect(parseDurationToSeconds('2 hours 30 minutes')).toBe(9000);
    expect(parseDurationToSeconds('45 seconds')).toBe(45);
  });

  it('formato reloj HH:MM:SS', () => {
    expect(parseDurationToSeconds('01:02:03')).toBe(3723);
  });

  it('sin datos devuelve null', () => {
    expect(parseDurationToSeconds('nada que ver')).toBeNull();
  });
});

describe('extractGcodeStats', () => {
  it('PrusaSlicer: tiempo + gramos directos', () => {
    const text = [
      '; generated by PrusaSlicer 2.7.1',
      'G28 ; home',
      '; estimated printing time (normal mode) = 2h 15m 30s',
      '; filament used [g] = 12.34',
      '; filament used [cm3] = 9.95',
    ].join('\n');
    expect(extractGcodeStats(text)).toEqual({ timeSeconds: 8130, grams: 12 });
  });

  it('OrcaSlicer: model printing time + total filament weight', () => {
    const text = [
      '; total filament weight [g] : 48.50',
      '; model printing time: 1h 23m 45s; total printing time: 1h 25m 12s',
      'M73 P99 R1200',
    ].join('\n');
    // "model printing time" tiene prioridad sobre M73
    expect(extractGcodeStats(text)).toEqual({ timeSeconds: 5025, grams: 49 });
  });

  it('Cura: TIME en segundos + filamento en metros → gramos PLA', () => {
    const text = [
      ';FLAVOR:Marlin',
      ';TIME:5678',
      ';Filament used: 3.42m',
      ';Layer height: 0.2',
    ].join('\n');
    // 3.42 m × π(0.0875 cm)² × 1.24 g/cm³ ≈ 10.20 → 10 g
    expect(extractGcodeStats(text)).toEqual({ timeSeconds: 5678, grams: 10 });
  });

  it('multi-extruder suma los gramos', () => {
    const text = ['; filament used [g] = 5.5, 4.5', '; estimated printing time (normal mode) = 10m'].join('\n');
    expect(extractGcodeStats(text)).toEqual({ timeSeconds: 600, grams: 10 });
  });

  it('PETG usa su densidad para convertir metros', () => {
    const text = [
      '; filament_type = PETG',
      '; filament_diameter = 1.75',
      '; Filament used: 1m',
      ';TIME:1000',
    ].join('\n');
    // 1 m × π(0.0875 cm)² × 1.27 g/cm³ ≈ 3.05 → 3 g
    expect(extractGcodeStats(text)).toEqual({ timeSeconds: 1000, grams: 3 });
  });

  it('M73 R como último recurso', () => {
    const text = 'M73 P50 R3600\nG1 X0 Y0';
    expect(extractGcodeStats(text)).toEqual({ timeSeconds: 3600, grams: null });
  });

  it('archivo sin metadatos no inventa nada', () => {
    const text = 'G28\nG1 X10 Y10 E1\nM104 S200';
    expect(extractGcodeStats(text)).toEqual({ timeSeconds: null, grams: null });
  });

  it('no se confunde con medidas mm del propio gcode', () => {
    const text = 'G1 X120.55 Y30.00 E0.0421 F1800\n; layer_height = 0.20mm';
    const stats = extractGcodeStats(text);
    expect(stats.timeSeconds).toBeNull();
  });
});
