-- Performance indexes for RLS company_id filtering + FK indexes
-- Generated by supabase-postgres-best-practices skill

-- company_id indexes (critical for RLS tenant isolation)
CREATE INDEX IF NOT EXISTS idx_deals_company_id ON deals (company_id);
CREATE INDEX IF NOT EXISTS idx_deliveries_company_id ON deliveries (company_id);
CREATE INDEX IF NOT EXISTS idx_expenses_company_id ON expenses (company_id);
CREATE INDEX IF NOT EXISTS idx_niches_company_id ON niches (company_id);
CREATE INDEX IF NOT EXISTS idx_packaging_supplies_company_id ON packaging_supplies (company_id);
CREATE INDEX IF NOT EXISTS idx_personalization_types_company_id ON personalization_types (company_id);
CREATE INDEX IF NOT EXISTS idx_profiles_company_id ON profiles (company_id);
CREATE INDEX IF NOT EXISTS idx_quotes_company_id ON quotes (company_id);
CREATE INDEX IF NOT EXISTS idx_raw_materials_company_id ON raw_materials (company_id);
CREATE INDEX IF NOT EXISTS idx_supplier_debts_company_id ON supplier_debts (company_id);
CREATE INDEX IF NOT EXISTS idx_suppliers_company_id ON suppliers (company_id);
CREATE INDEX IF NOT EXISTS idx_treasury_company_id ON treasury (company_id);
CREATE INDEX IF NOT EXISTS idx_worker_tasks_company_id ON worker_tasks (company_id);
CREATE INDEX IF NOT EXISTS idx_workers_company_id ON workers (company_id);

-- FK indexes for stock_movements
CREATE INDEX IF NOT EXISTS idx_stock_movements_product_id ON stock_movements (product_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_size_id ON stock_movements (size_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_color_id ON stock_movements (color_id);
